line-length = 88

[format]
quote-style = "single"

[lint]
ignore = [
   "D203", # a blank line before class docstrings
   "D212", # no line break after opening quote in multi-line docstring
]
extend-select = [
  "D",   # check docstrings
  "B",   # flake8-bugbear
  "I",   # isort
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
  "UP",  # pyupgrade
  "N",   # naming
  "F",   # pyflakes
  "C90", # complexity
]
